---
name: CI

on:
  push:
    branches: [main, dev]
    paths-ignore:
      - '**.md'
      - 'LICENSE*'
      - '.gitignore'
  pull_request:
    branches: [main, dev]
    paths-ignore:
      - '**.md'
      - 'LICENSE*'
      - '.gitignore'

jobs:
  ci:
    uses: riccione/github-workflows/.github/workflows/rust-ci.yml@309464f75695501b26e988010273cc182de38f3a
