---
name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  CLI_BIN: nomforge-cli
  GUI_BIN: nomforge-gui

jobs:
  release:
    uses: riccione/github-workflows/.github/workflows/rust-release.yml@2fb7292b498ec2e19c534cb1bd5c651e896f5714
    with:
      tag: ${{ github.ref_name }}
      bin_names: "nomforge-cli nomforge-gui"
      apt_packages: "libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libgtk-3-dev libatk1.0-dev libgdk-pixbuf2.0-dev libpango1.0-dev libcairo2-dev"
      use_upx: true
      cargo_args: "--locked"
    secrets: inherit
